server:
  port: 18080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/accounts
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: WUseng2020
  redis:
    database: 0
    host: localhost
    port: 6379
    timeout: 100
    lettuce:
      pool:
        max-active: 100
        max-wait: 100
        max-idle: 10
        min-idle: 0
  task:
    execution:
      pool:
        core-size: 20
        max-size: 40
        keep-alive: 40s
        queue-capacity: 100

logging:
  config: classpath:logback-spring.xml
